# Generated by Django 5.0.6 on 2024-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
