# Generated by Django 5.0.6 on 2024-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marks',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.mark'),
        ),
    ]
