# Generated by Django 5.0.6 on 2024-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='content',
        ),
        migrations.AddField(
            model_name='mark',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
